### ISSUE TITLE
Unnecessary dependency on 'jq'

### ISSUE THREAD

**Issue by bear454** [vmware/open-vmdk#3]
https://github.com/vmware/open-vmdk/blob/master/ova/mkova.sh#L47 invokes `jq` in order to parse an attribute out of a short JSON snippet. For that size of input, the value could be easily handled using more prevalent command line tools.

Please note as well, `jq` is _not_ supported on SUSE Linux Enterprise.

**Comment by JacobAMason** [comment]
This is closed by #6
