### ISSUE TITLE
Incorrect tools version in metadata

### ISSUE THREAD

**Issue by bear454** [vmware/open-vmdk#4]
https://github.com/vmware/open-vmdk/blob/master/vmdk/sparse.c#L165

`dbb.toolsVersion` is always written with an incorrect version.

In the event that vm-tools are not installed, the managing app running this VMDK will incorrectly detect and try to use vm-tools, causing cascaded issues.

In the event the VMDK used as input already has a toolsVersion written, it should be respected, instead of over-writing with a known incorrect version number.

**Comment by keirazhang** [comment]
Added a `-t` option to set ddb.toolsVersion. See README for details.
