### ISSUE TITLE
`mkova.sh` keeps going when `vmdk_convert` not found

### ISSUE THREAD

**Issue by clebs** [vmware/open-vmdk#60]
### Describe the bug

When running `mkova.sh`, if the command `vmdk-convert` is not in the PATH, it continues running and creates the OVA with empty capacity.

### Reproduction steps

1. Make sure `vmd_convert` is not availabel on the PATH
2. Run `mkova.sh` with all needed parameters.
3. See output.

### Expected behavior

The script stops and errors out if `vmdk-convert` is not present.

### Additional context

Output of running the script when `vmdk-convert` is not available:
```
Starting to create testOVA.ova with 1 disk(s) with template ./share/open-vmdk/template-hw21.ovf
Number of CPUs: 4
Memory in MB: 4096
Firmware Type: efi
Adding ./vagrantbox.vmdk as testOVA-disk1.vmdk
./vagrantbox.vmdk file size is 1164496896 bytes
./bin/mkova.sh: line 139: vmdk-convert: command not found
./vagrantbox.vmdk capacity is  bytes
~/open-vmdk/Dwo2w6mn ~/open-vmdk
~/open-vmdk
Completed to create testOVA.ova

```

**Comment by oliverkurth** [comment]
Thanks for reporting.

I can fix this, but please note that `mkova.sh` is deprecated - please use `ova-compose` instead.

**Comment by clebs** [comment]
Thanks!

Yes I am aware, but for my use case the shell script is easier because I do not need to install python and its libs on my vm/container.

**Comment by oliverkurth** [comment]
Please see #61 .

**Comment by clebs** [comment]
That was really fast thank you!
