### ISSUE TITLE
Check and modify metadata in VMDK

### ISSUE THREAD

**Issue by keirazhang** [vmware/open-vmdk#9]
For existing OVF/OVA, if the ddb.toolsVersion missing in VMDK metadata, it would block guest customization performing. VMware KB https://kb.vmware.com/s/article/83068 describes one solution with VDDK. 
We need to expand the functionality of open-vmdk to check a VMDK in existing OVF/OVA and modify it.

**Comment by oliverkurth** [comment]
@keirazhang I think this is resolved?

**Comment by oliverkurth** [comment]
IIUC, this is about the tools version. This has been fixed in PR #11 .
